# react-native-svga consumer ProGuard / R8 rules
#
# Nitro Modules looks up these classes by their fully-qualified name from
# native (JNI) code. R8/ProGuard must not rename or remove them, nor strip
# any of their fields/methods that Nitro touches reflectively.

-keep class com.margelo.nitro.svga.HybridSvga { *; }
-keep class com.margelo.nitro.svga.HybridSvgaManager { *; }
-keep class com.margelo.nitro.svga.HybridSvgaSpec { *; }
-keep class com.margelo.nitro.svga.HybridSvgaManagerSpec { *; }
-keep class com.margelo.nitro.svga.ScaleMode { *; }
-keep class com.margelo.nitro.svga.views.** { *; }
-keep class com.margelo.nitro.svga.SvgaPackage { *; }

# Function adapters generated by Nitrogen (Func_void, Func_void_double, etc.).
-keep class com.margelo.nitro.svga.Func_void* { *; }

# The Nitro callback annotations rely on the names being preserved.
-keepattributes *Annotation*
